---

- name: Install Apache2
  hosts: webserver
  become: yes  # Use sudo to install packages
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

